export const countries = [
  { country: 'Belgium', countryIsoCode: 'BE' },
  { country: 'Bulgaria', countryIsoCode: 'BG' },
  { country: 'Chile', countryIsoCode: 'CL' },
  { country: 'China', countryIsoCode: 'CN' },
  { country: 'Colombia', countryIsoCode: 'CO' },
  { country: 'Egypt', countryIsoCode: 'EG' },
  { country: 'Finland', countryIsoCode: 'FI' },
  { country: 'France', countryIsoCode: 'FR' },
  { country: 'Germany', countryIsoCode: 'DE' },
  { country: 'Hong Kong', countryIsoCode: 'HK' },
  { country: 'India', countryIsoCode: 'IN' },
  { country: 'Ireland', countryIsoCode: 'IE' },
  { country: 'Italy', countryIsoCode: 'IT' },
  { country: 'Japan', countryIsoCode: 'JP' },
  { country: 'Kenya', countryIsoCode: 'KE' },
  { country: 'Macau', countryIsoCode: 'MO' },
  { country: 'Malta', countryIsoCode: 'MT' },
  { country: 'Mexico', countryIsoCode: 'MX' },
  { country: 'New Zealand', countryIsoCode: 'NZ' },
  { country: 'Peru', countryIsoCode: 'PE' },
  { country: 'Spain', countryIsoCode: 'ES' },
  { country: 'Taiwan', countryIsoCode: 'TW' },
  { country: 'Thailand', countryIsoCode: 'TH' },
  { country: 'United Kingdom', countryIsoCode: 'GB' },
  { country: 'United States', countryIsoCode: 'US' },
];
