export const hotels = [
  {
    chainName: 'Samed Resorts Group',
    hotelName: 'Sai Kaew Beach Resort',
    addressLine1: '8/1 Moo 4 Tumbon Phe Muang',
    addressLine2: '',
    zipCode: '21160',
    city: 'Koh Samet',
    state: 'Rayong',
    country: 'Thailand',
    countryIsoCode: 'TH',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Marine Hotel',
    addressLine1: 'Sutton Cross',
    addressLine2: '',
    zipCode: 'D13',
    city: 'Dublin',
    state: '',
    country: 'Ireland',
    countryIsoCode: 'IE',
    starRating: 3,
  },
  {
    chainName: 'Melia Hotels International',
    hotelName: 'TRYP Malaga Alameda Hotel',
    addressLine1: 'Avenida de la Aurora CC.Larios Centro S/N',
    addressLine2: '',
    zipCode: '29002',
    city: 'Malaga',
    state: 'Andalusia',
    country: 'Spain',
    countryIsoCode: 'ES',
    starRating: 4,
  },
  {
    chainName: 'NH Hotels',
    hotelName: 'NH Iquique Hotel',
    addressLine1: 'Av Costanera 3939',
    addressLine2: '',
    zipCode: '1111500',
    city: 'Iquique',
    state: 'Tarapacá',
    country: 'Chile',
    countryIsoCode: 'CL',
    starRating: 4,
  },
  {
    chainName: 'Marriott',
    hotelName: 'Sheraton Grand Hotel & Spa, Edinburgh',
    addressLine1: '1 Festival Square',
    addressLine2: '',
    zipCode: 'EH39SR',
    city: 'Edinburgh',
    state: 'Scotland',
    country: 'United Kingdom',
    countryIsoCode: 'GB',
    starRating: 5,
  },
  {
    chainName: 'HK CTS Hotels',
    hotelName: 'Kew Green Hotel Wanchai Hong Kong',
    addressLine1: '41-49 Hennessy Road',
    addressLine2: '',
    zipCode: '',
    city: 'Hong Kong',
    state: 'Hong Kong',
    country: 'Hong Kong',
    countryIsoCode: 'HK',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Hotel Dann Carlton Medellin',
    addressLine1: 'Cra 43A No. 7-50',
    addressLine2: '',
    zipCode: '50001',
    city: 'Medellin',
    state: '',
    country: 'Colombia',
    countryIsoCode: 'CO',
    starRating: 5,
  },
  {
    chainName: 'No chain',
    hotelName: 'Grand Coloane Resort',
    addressLine1: '1918 Estrada de Hac Sa',
    addressLine2: '',
    zipCode: '',
    city: 'Macau',
    state: 'Macao',
    country: 'Macau',
    countryIsoCode: 'MO',
    starRating: 5,
  },
  {
    chainName: 'Skycity',
    hotelName: 'SKYCITY Hotel',
    addressLine1: 'Corner Victoria & Federal Streets',
    addressLine2: '',
    zipCode: '1010',
    city: 'Auckland',
    state: 'Auckland',
    country: 'New Zealand',
    countryIsoCode: 'NZ',
    starRating: 4.5,
  },
  {
    chainName: 'Accor Hotels',
    hotelName: 'Pullman Bordeaux Lac',
    addressLine1: 'Avenue Jean Gabriel Domergue',
    addressLine2: '',
    zipCode: '33300',
    city: 'Bordeaux',
    state: 'Aquitaine',
    country: 'France',
    countryIsoCode: 'FR',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Hotel Conde Luna',
    addressLine1: 'Avenida Independencia, 7',
    addressLine2: '',
    zipCode: '24003',
    city: 'Leon',
    state: '',
    country: 'Spain',
    countryIsoCode: 'ES',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Park Suisse Hotel',
    addressLine1: 'Via Favale 31',
    addressLine2: '',
    zipCode: '16038',
    city: 'Santa Margherita Ligure',
    state: 'Liguria',
    country: 'Italy',
    countryIsoCode: 'IT',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Hotel Agua Escondida',
    addressLine1: 'Guillermo Spartling, 4 Centro ',
    addressLine2: '',
    zipCode: '40200',
    city: 'Taxco',
    state: '',
    country: 'Mexico',
    countryIsoCode: 'MX',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Hotel Caribe Cartagena',
    addressLine1: 'Carrera 1, 2-87, Bocagrande',
    addressLine2: '',
    zipCode: '130001',
    city: 'Cartagena',
    state: 'Bolivar',
    country: 'Colombia',
    countryIsoCode: 'CO',
    starRating: 5,
  },
  {
    chainName: 'No chain',
    hotelName: 'Haihua Hotel Hangzhou',
    addressLine1: 'No. 298, Qing Chun Road',
    addressLine2: '',
    zipCode: '310006',
    city: 'Hangzhou',
    state: 'Zhejiang',
    country: 'China',
    countryIsoCode: 'CN',
    starRating: 4,
  },
  {
    chainName: 'Tokyu Hotels',
    hotelName: 'Kobe Sannomiya Tokyu REI Hotel',
    addressLine1: '6-1-5 Kumoidori, Chuo-ku',
    addressLine2: '',
    zipCode: '651-0096',
    city: 'Kobe',
    state: 'Hyogo',
    country: 'Japan',
    countryIsoCode: 'JP',
    starRating: 3,
  },
  {
    chainName: 'No chain',
    hotelName: 'Suites South Burlington',
    addressLine1: '1712 Shelburne Rd.',
    addressLine2: '',
    zipCode: '5403',
    city: 'So Burlington (VT)',
    state: 'Vermont',
    country: 'United States',
    countryIsoCode: 'US',
    starRating: 2.5,
  },
  {
    chainName: 'No chain',
    hotelName: 'Everbright Convention & Exhibition Centre International Hotel',
    addressLine1: '66 Caobao Road, Xuhui district',
    addressLine2: '',
    zipCode: '',
    city: 'Shanghai',
    state: 'Shanghai',
    country: 'China',
    countryIsoCode: 'CN',
    starRating: 4,
  },
  {
    chainName: 'Hilton Worldwide',
    hotelName: 'Hilton Garden Inn Pittsburgh University Place',
    addressLine1: '3454 Forbes Avenue',
    addressLine2: '',
    zipCode: '15213',
    city: 'Pittsburgh (PA)',
    state: 'Pennsylvania',
    country: 'United States',
    countryIsoCode: 'US',
    starRating: 3,
  },
  {
    chainName: 'No chain',
    hotelName: 'Hotel Apogia Nice',
    addressLine1: '26, Rue Smolett',
    addressLine2: '',
    zipCode: '6300',
    city: 'Nice',
    state: "Provence-Alpes-Cote d'Azur",
    country: 'France',
    countryIsoCode: 'FR',
    starRating: 4,
  },
  {
    chainName: 'Caesars Entertainment Corporation',
    hotelName: 'Paris Las Vegas',
    addressLine1: '3655 Las Vegas Boulevard South',
    addressLine2: '',
    zipCode: '89109',
    city: 'Las Vegas (NV)',
    state: 'Nevada',
    country: 'United States',
    countryIsoCode: 'US',
    starRating: 4,
  },
  {
    chainName: 'Hoteles Catalonia',
    hotelName: 'Catalonia Brussels Hotel',
    addressLine1: 'Avenue du Haut-Pont, 2 Hoge Bruglaan',
    addressLine2: '',
    zipCode: 'B1060',
    city: 'Brussels',
    state: 'Brussels-Capital',
    country: 'Belgium',
    countryIsoCode: 'BE',
    starRating: 3,
  },
  {
    chainName: 'Prince Hotels',
    hotelName: 'Grand Prince Hotel Shin Takanawa',
    addressLine1: '3-13-1 Takanawa, Minato-ku',
    addressLine2: '',
    zipCode: '108-8612',
    city: 'Tokyo',
    state: 'Tokyo',
    country: 'Japan',
    countryIsoCode: 'JP',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Watazen Ryokan Hotel',
    addressLine1: '604-8113 Nakagyo-ku Yanaginobaba-dori Rokkaku-kudaru 413',
    addressLine2: '',
    zipCode: '604-8113',
    city: 'Kyoto',
    state: 'Kyoto',
    country: 'Japan',
    countryIsoCode: 'JP',
    starRating: 3,
  },
  {
    chainName: 'Thistle & Guoman',
    hotelName: 'Amba Hotel Charing Cross',
    addressLine1: 'The Strand',
    addressLine2: '',
    zipCode: 'WC2N 5HX',
    city: 'London',
    state: 'London, England',
    country: 'United Kingdom',
    countryIsoCode: 'GB',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Imperial Hotel',
    addressLine1: '32-34 Nathan Road',
    addressLine2: '',
    zipCode: '',
    city: 'Hong Kong',
    state: 'Hong Kong',
    country: 'Hong Kong',
    countryIsoCode: 'HK',
    starRating: 3,
  },
  {
    chainName: 'Leading Hotels of the World',
    hotelName: 'Royal Hotel Sanremo',
    addressLine1: '80 Corso Imperatrice',
    addressLine2: '',
    zipCode: '18038',
    city: 'Sanremo',
    state: '',
    country: 'Italy',
    countryIsoCode: 'IT',
    starRating: 5,
  },
  {
    chainName: 'Park Hotels',
    hotelName: 'The Park Hotel Visakhapatnam',
    addressLine1: 'Beach road',
    addressLine2: '',
    zipCode: '530023',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    countryIsoCode: 'IN',
    starRating: 5,
  },
  {
    chainName: 'InterContinental Hotels Group',
    hotelName: 'Staybridge Suites Austin Round Rock',
    addressLine1: '520 S IH 35 Frontage Rd',
    addressLine2: '',
    zipCode: '78681',
    city: 'Round Rock (TX)',
    state: 'Texas',
    country: 'United States',
    countryIsoCode: 'US',
    starRating: 3,
  },
  {
    chainName: 'Sotetsu Fresa Inn',
    hotelName: 'Hotel Sunroute Nara',
    addressLine1: '1110 Takabatake-cho',
    addressLine2: '',
    zipCode: '630-8301',
    city: 'Nara',
    state: 'Nara',
    country: 'Japan',
    countryIsoCode: 'JP',
    starRating: 3,
  },
  {
    chainName: 'Thistle & Guoman',
    hotelName: 'The Tower Hotel',
    addressLine1: "St Katharine's Way",
    addressLine2: '',
    zipCode: 'E1W 1LD',
    city: 'London',
    state: 'London, England',
    country: 'United Kingdom',
    countryIsoCode: 'GB',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'The Grand New Delhi Hotel',
    addressLine1: 'Nelson Mandela Road, Vasant Kunj, Phase II',
    addressLine2: '',
    zipCode: '110070',
    city: 'New Delhi and NCR',
    state: 'Delhi National Territory',
    country: 'India',
    countryIsoCode: 'IN',
    starRating: 5,
  },
  {
    chainName: 'Corinthia Hotels International',
    hotelName: 'Corinthia Hotel St. George’s Bay',
    addressLine1: 'St. George`s Bay',
    addressLine2: '',
    zipCode: 'STJ 3301',
    city: "St. Julian's",
    state: 'Malta',
    country: 'Malta',
    countryIsoCode: 'MT',
    starRating: 5,
  },
  {
    chainName: 'Blue Sea Hotels & Resorts',
    hotelName: 'Gran Hotel Cervantes by Blue Sea',
    addressLine1: 'Las Mercedes s/n',
    addressLine2: '',
    zipCode: '29620',
    city: 'Torremolinos',
    state: 'Andalusia',
    country: 'Spain',
    countryIsoCode: 'ES',
    starRating: 4,
  },
  {
    chainName: 'InterContinental Hotels Group',
    hotelName: 'Hotel Intercontinental Cali',
    addressLine1: 'Av. Colombia No. 2-72',
    addressLine2: '',
    zipCode: '760001',
    city: 'Cali',
    state: 'Valle del Cauca',
    country: 'Colombia',
    countryIsoCode: 'CO',
    starRating: 4.5,
  },
  {
    chainName: 'Oberoi Hotels & Resorts',
    hotelName: 'The Oberoi Rajvilas Jaipur Hotel',
    addressLine1: 'Goner Road',
    addressLine2: '',
    zipCode: '303012',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    countryIsoCode: 'IN',
    starRating: 5,
  },
  {
    chainName: 'No chain',
    hotelName: 'Mariel Hotel Boutique',
    addressLine1: 'General Belisario Suarez, 240 - Miraflores',
    addressLine2: '',
    zipCode: 'Lima18',
    city: 'Lima',
    state: '',
    country: 'Peru',
    countryIsoCode: 'PE',
    starRating: 3,
  },
  {
    chainName: 'No chain',
    hotelName: 'Hilton Hurghada Long Beach Resort',
    addressLine1: 'Sahl Hashish Red Sea',
    addressLine2: '',
    zipCode: '                    ',
    city: 'Hurghada',
    state: 'Al Bahr al Ahmar',
    country: 'Egypt',
    countryIsoCode: 'EG',
    starRating: 3,
  },
  {
    chainName: 'Daiwa Royal Hotel',
    hotelName: 'Royal Hotel MUNAKATA',
    addressLine1: '1303 Tano, Munakata-shi',
    addressLine2: '',
    zipCode: '811-3514',
    city: 'Munakata',
    state: 'Fukuoka',
    country: 'Japan',
    countryIsoCode: 'JP',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Gioberti Hotel',
    addressLine1: 'Via Gioberti 20',
    addressLine2: '',
    zipCode: '185',
    city: 'Rome',
    state: 'Lazio',
    country: 'Italy',
    countryIsoCode: 'IT',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Hotel Serrano',
    addressLine1: 'Marques de Villamejor, 8',
    addressLine2: '',
    zipCode: '28006',
    city: 'Madrid',
    state: 'Madrid',
    country: 'Spain',
    countryIsoCode: 'ES',
    starRating: 4,
  },
  {
    chainName: '',
    hotelName: 'Sarova Whitesands Beach Resort & Spa',
    addressLine1: 'Nyali/Malindi Highway',
    addressLine2: '',
    zipCode: '801',
    city: 'Mombasa',
    state: 'Mombasa',
    country: 'Kenya',
    countryIsoCode: 'KE',
    starRating: 5,
  },
  {
    chainName: 'No chain',
    hotelName: 'Scandic Seinajoki',
    addressLine1: 'Kauppakatu 10',
    addressLine2: '',
    zipCode: '60100',
    city: 'Seinajoki',
    state: '',
    country: 'Finland',
    countryIsoCode: 'FI',
    starRating: 4,
  },
  {
    chainName: 'No chain',
    hotelName: 'Van der Valk Hotel Hildesheim',
    addressLine1: 'Markt 4, GPS: Jakobistraße',
    addressLine2: '',
    zipCode: '31134',
    city: 'Hildesheim',
    state: '',
    country: 'Germany',
    countryIsoCode: 'DE',
    starRating: 4,
  },
  {
    chainName: 'Marriott',
    hotelName: 'Sheraton Grand Taipei Hotel',
    addressLine1: 'No.12, Sec. 1, Zhongxiao E. Rd',
    addressLine2: '',
    zipCode: '10049',
    city: 'Taipei',
    state: 'Taipei City',
    country: 'Taiwan',
    countryIsoCode: 'TW',
    starRating: 5,
  },
  {
    chainName: 'InterContinental Hotels Group',
    hotelName: 'Holiday Inn Express London Greenwich',
    addressLine1: 'Bugsbys Way',
    addressLine2: '',
    zipCode: 'SE10 0GD',
    city: 'London',
    state: 'London, England',
    country: 'United Kingdom',
    countryIsoCode: 'GB',
    starRating: 3.5,
  },
  {
    chainName: 'No chain',
    hotelName: 'Bulgaria Hotel',
    addressLine1: '21 Alexandrovska Street',
    addressLine2: '',
    zipCode: '8000',
    city: 'Burgas',
    state: '',
    country: 'Bulgaria',
    countryIsoCode: 'BG',
    starRating: 4,
  },
];
